# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 12:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='photoCollection',
            fields=[
                ('photoCollection_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'photoCollection',
            },
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=60)),
                ('securityQuestion', models.CharField(max_length=240)),
                ('securityAnswer', models.CharField(max_length=240)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='contactInfo',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='a.users')),
                ('mobileNo', models.IntegerField()),
                ('landlineNo', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'contactInfo',
            },
        ),
        migrations.CreateModel(
            name='generalSettings',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='a.users')),
                ('language', models.CharField(max_length=240)),
                ('timezone', models.CharField(max_length=240)),
                ('country', models.CharField(max_length=240)),
            ],
            options={
                'db_table': 'generalSettings',
            },
        ),
        migrations.CreateModel(
            name='personalInfo',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='a.users')),
                ('firstname', models.CharField(max_length=240)),
                ('surname', models.CharField(max_length=240)),
                ('gender', models.CharField(max_length=240)),
                ('birthday', models.DateField()),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'personalInfo',
            },
        ),
        migrations.CreateModel(
            name='securitySettings',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='a.users')),
                ('whocanseeblog', models.CharField(max_length=240)),
                ('whocanseeprofile', models.CharField(max_length=240)),
                ('limitNoVisiblePastPosts', models.CharField(max_length=240)),
                ('limitDateVisiblePosts', models.CharField(max_length=240)),
                ('whoCanSendFriendRequests', models.CharField(max_length=240)),
                ('visibleName', models.CharField(max_length=240)),
                ('visiblePersonalInfo', models.BooleanField()),
                ('visibleContactInfo', models.BooleanField()),
            ],
            options={
                'db_table': 'securitySettings',
            },
        ),
        migrations.CreateModel(
            name='settings',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='a.users')),
            ],
            options={
                'db_table': 'settings',
            },
        ),
        migrations.AddField(
            model_name='photocollection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a.users'),
        ),
    ]
