# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogpostcomments',
            fields=[
                ('commentId', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=240)),
                ('dateTime', models.DateTimeField()),
            ],
            options={
                'db_table': 'blogpostcomments',
            },
        ),
        migrations.CreateModel(
            name='blogposts',
            fields=[
                ('postID', models.AutoField(primary_key=True, serialize=False)),
                ('blogTitle', models.CharField(max_length=240)),
                ('dateTime', models.DateTimeField()),
                ('blogPostBody', models.CharField(max_length=240)),
            ],
            options={
                'db_table': 'blogposts',
            },
        ),
        migrations.CreateModel(
            name='blogs',
            fields=[
                ('blogID', models.AutoField(primary_key=True, serialize=False)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a.users')),
            ],
            options={
                'db_table': 'blogs',
            },
        ),
        migrations.CreateModel(
            name='photoComments',
            fields=[
                ('commentId', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=60)),
                ('dateTime', models.DateTimeField()),
                ('byUserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a.users')),
            ],
            options={
                'db_table': 'photoComments',
            },
        ),
        migrations.CreateModel(
            name='photos',
            fields=[
                ('photoID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('caption', models.CharField(max_length=60)),
                ('dateUploaded', models.DateTimeField()),
                ('photoCollectionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a.photoCollection')),
            ],
            options={
                'db_table': 'photos',
            },
        ),
        migrations.AddField(
            model_name='photocomments',
            name='photoId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a.photos'),
        ),
        migrations.AddField(
            model_name='blogposts',
            name='blogID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a.blogs'),
        ),
        migrations.AddField(
            model_name='blogpostcomments',
            name='blogId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a.blogs'),
        ),
        migrations.AddField(
            model_name='blogpostcomments',
            name='blogPostId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a.blogposts'),
        ),
        migrations.AddField(
            model_name='blogpostcomments',
            name='byUserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a.users'),
        ),
    ]
